# Docker compose
version: '3.7'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kpac
    ports:
      - "3306:3306"
    volumes:
      # Uncomment the following lines to persist the data in a local folder
      #- ./mysql:/var/lib/mysql
      - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/1.sql:ro
      - ./src/main/resources/database/data.sql:/docker-entrypoint-initdb.d/2.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat
    restart: always
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/kpac
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      mysql:
        condition: service_healthy